name: FlowerPower
main: com.electro2560.dev.flowerpower.FlowerPower
version: ${project.version}
api-version: 1.13
website: https://dev.electro2560.com/
author: electro2560
description: Flowers have powers!